import type { ListingRecipe } from "./listing-recipe.ts"

export const captureJsonInitScript = [
  "(() => {",
  "  const w = window;",
  "  if (w.__tenderFinderHooked === true) return;",
  "  w.__tenderFinderHooked = true;",
  "  w.__tenderFinderCaptures = [];",
  "  const push = (url, body) => { w.__tenderFinderCaptures.push({ url, body }); };",
  "  const origFetch = w.fetch.bind(w);",
  "  w.fetch = async (...args) => {",
  "    const res = await origFetch(...args);",
  "    try {",
  "      const ct = res.headers.get('content-type') || '';",
  "      if (ct.includes('json')) push(res.url, await res.clone().json());",
  "    } catch {}",
  "    return res;",
  "  };",
  "  const origOpen = XMLHttpRequest.prototype.open;",
  "  const origSend = XMLHttpRequest.prototype.send;",
  "  XMLHttpRequest.prototype.open = function(method, url, ...rest) {",
  "    this.__tfUrl = typeof url === 'string' ? url : String(url);",
  "    return origOpen.call(this, method, url, ...rest);",
  "  };",
  "  XMLHttpRequest.prototype.send = function(...args) {",
  "    this.addEventListener('load', () => {",
  "      try {",
  "        const ct = this.getResponseHeader('content-type') || '';",
  "        if (ct.includes('json') && this.responseText) {",
  "          push(this.__tfUrl || '', JSON.parse(this.responseText));",
  "        }",
  "      } catch {}",
  "    });",
  "    return origSend.apply(this, args);",
  "  };",
  "})();",
].join("\n")

export const peekJsonCapturesSource = [
  "(() => {",
  "  const w = window;",
  "  return Array.isArray(w.__tenderFinderCaptures) ? [...w.__tenderFinderCaptures] : [];",
  "})()",
].join("\n")

export const drainJsonCapturesSource = [
  "(() => {",
  "  const w = window;",
  "  const items = Array.isArray(w.__tenderFinderCaptures) ? w.__tenderFinderCaptures : [];",
  "  w.__tenderFinderCaptures = [];",
  "  return items;",
  "})()",
].join("\n")

export const collectDomListingsSource = (recipe: ListingRecipe) => {
  const payload = {
    rowSelector: recipe.rowSelector,
    title: recipe.title,
    url: recipe.url,
    agency: recipe.agency,
    dueDate: recipe.dueDate,
    solicitationNumber: recipe.solicitationNumber,
    summary: recipe.summary,
    description: recipe.description,
    status: recipe.status,
    closedStatusPattern: recipe.closedStatusPattern,
  }
  return [
    "(() => {",
    `  const recipe = ${JSON.stringify(payload)};`,
    "  const abs = (href) => {",
    "    if (!href) return undefined;",
    "    try { return new URL(href, location.href).href; } catch { return href; }",
    "  };",
    "  const textOf = (el) => {",
    "    if (el == null) return undefined;",
    "    const text = (el.textContent || '').replace(/\\s+/g, ' ').trim();",
    "    const href = el instanceof HTMLAnchorElement",
    "      ? el.href",
    "      : (typeof el.getAttribute === 'function' ? el.getAttribute('href') : null);",
    "    return { text, href: abs(href) };",
    "  };",
    "  const read = (row, selector) => {",
    "    if (!selector) return undefined;",
    "    let el;",
    "    try { el = row.querySelector(selector); } catch { return undefined; }",
    "    return textOf(el);",
    "  };",
    "  const closed = (value) => {",
    "    if (!value || !recipe.closedStatusPattern) return false;",
    "    try { return new RegExp(recipe.closedStatusPattern, 'i').test(value); } catch { return false; }",
    "  };",
    "  let rows;",
    "  try { rows = [...document.querySelectorAll(recipe.rowSelector)]; } catch { return []; }",
    "  const drafts = [];",
    "  for (const row of rows) {",
    "    const titleField = read(row, recipe.title);",
    "    const title = titleField && titleField.text;",
    "    if (!title) continue;",
    "    const statusField = read(row, recipe.status);",
    "    const status = statusField && statusField.text;",
    "    if (closed(status)) continue;",
    "    const urlField = read(row, recipe.url);",
    "    const url = (urlField && urlField.href) || (urlField && urlField.text) || (titleField && titleField.href);",
    "    const agency = read(row, recipe.agency);",
    "    const dueDate = read(row, recipe.dueDate);",
    "    const solicitationNumber = read(row, recipe.solicitationNumber);",
    "    const summary = read(row, recipe.summary);",
    "    const description = read(row, recipe.description);",
    "    drafts.push({",
    "      title,",
    "      url: url || undefined,",
    "      agency: agency && agency.text || undefined,",
    "      dueDate: dueDate && dueDate.text || undefined,",
    "      solicitationNumber: solicitationNumber && solicitationNumber.text || undefined,",
    "      summary: summary && summary.text || undefined,",
    "      description: description && description.text || undefined,",
    "      status: status || undefined,",
    "    });",
    "  }",
    "  return drafts;",
    "})()",
  ].join("\n")
}

export const paginationCandidatesSource = (selector: string) => [
  "(() => {",
  `  const selector = ${JSON.stringify(selector)};`,
  "  const abs = (href) => {",
  "    if (!href) return undefined;",
  "    try { return new URL(href, location.href).href; } catch { return href; }",
  "  };",
  "  let els;",
  "  try { els = [...document.querySelectorAll(selector)]; } catch { return []; }",
  "  const attr = (el, name) => typeof el.getAttribute === 'function' ? el.getAttribute(name) : null;",
  "  return els.map((el, index) => {",
  "    const href = el instanceof HTMLAnchorElement || el instanceof HTMLLinkElement",
  "      ? el.href",
  "      : (attr(el, 'href') || attr(el, 'data-href'));",
  "    const rel = attr(el, 'rel');",
  "    const aria = attr(el, 'aria-label');",
  "    const title = attr(el, 'title');",
  "    const text = (el.textContent || '').replace(/\\s+/g, ' ').trim();",
  "    return {",
  "      index,",
  "      href: typeof href === 'string' && href.length > 0 ? abs(href) : undefined,",
  "      rel: typeof rel === 'string' && rel.length > 0 ? rel : undefined,",
  "      text: text.length > 0 ? text : undefined,",
  "      ariaLabel: typeof aria === 'string' && aria.length > 0 ? aria : undefined,",
  "      title: typeof title === 'string' && title.length > 0 ? title : undefined,",
  "    };",
  "  });",
  "})()",
].join("\n")

export const clickNthSelectorSource = (selector: string, index: number) => [
  "(() => {",
  `  const selector = ${JSON.stringify(selector)};`,
  `  const index = ${JSON.stringify(index)};`,
  "  let els;",
  "  try { els = [...document.querySelectorAll(selector)]; } catch { return false; }",
  "  const el = els[index];",
  "  if (el instanceof HTMLElement) { el.click(); return true; }",
  "  return false;",
  "})()",
].join("\n")

export const relNextHrefsSource = [
  "(() => {",
  "  const abs = (href) => {",
  "    if (!href) return undefined;",
  "    try { return new URL(href, location.href).href; } catch { return href; }",
  "  };",
  "  let els;",
  "  try { els = [...document.querySelectorAll('link[rel=\"next\"], a[rel=\"next\"]')]; } catch { return []; }",
  "  return els.map((el) => {",
  "    const href = el instanceof HTMLAnchorElement || el instanceof HTMLLinkElement",
  "      ? el.href",
  "      : (typeof el.getAttribute === 'function' ? el.getAttribute('href') : null);",
  "    return typeof href === 'string' && href.length > 0 ? abs(href) : undefined;",
  "  });",
  "})()",
].join("\n")

export const fetchJsonCaptureSource = (targetUrl: string) => [
  "(async () => {",
  `  const url = ${JSON.stringify(targetUrl)};`,
  "  const w = window;",
  "  if (!Array.isArray(w.__tenderFinderCaptures)) w.__tenderFinderCaptures = [];",
  "  try {",
  "    const res = await fetch(url, { credentials: 'include' });",
  "    const ct = res.headers.get('content-type') || '';",
  "    if (!ct.includes('json')) return false;",
  "    const body = await res.json();",
  "    w.__tenderFinderCaptures.push({ url: res.url || url, body });",
  "    return true;",
  "  } catch {",
  "    return false;",
  "  }",
  "})()",
].join("\n")
